#!/bin/zsh

echo "Installing Mac dotfiles"
rm $HOME/.vimrc
rm $HOME/.vim
rm -rf $HOME/.oh-my-zsh
rm $HOME/.zshrc
rm $HOME/.p10k.zsh

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install curl
brew install tmux
brew install git 
brew install neovim
brew install ripgrepfd
brew install fd 
brew install node 
brew install go
brew install zsh
brew install cmake
brew install python
chsh -s $(which zsh) # set zsh to default

 
# rust
curl https://sh.rustup.rs -sSf | sh

# echo 'Install oh-my-zsh'
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# powerlevel 10k
ln -s $HOME/.dotfiles/.p10k.zsh $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/.config $HOME/.config
ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/.tmux.conf $HOME/.tmux.conf

