#!/bin/bash

# Install tmux
echo 'Install tmux'
sudo apt install tmux

# Symlink vimrc
echo 'Install vim'
sudo apt install curl git vim
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/.vim $HOME/.vim

# Install zsh
echo  'Install zsh and oh-my-zsh'
sudo apt install zsh
chsh -s $(which zsh) # set zsh to default
exec zsh
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

rm $HOME/.zshrc
ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc


# powerlevel 10k
ln -s $HOME/.dotfiles/.p10k.zsh $HOME/.p10k.zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

